###
# Criar categoria
POST {{baseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Manutenção"
}

###
# Listar categorias
GET {{baseUrl}}/categories
Authorization: Bearer {{token}}

###
# Buscar categoria por ID
GET {{baseUrl}}/categories/51e05e33-ccca-430c-999a-a30fb94acc36
Authorization: Bearer {{token}}