###
# Criar transação
POST {{baseUrl}}/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": 100.50,
  "description": "Supermercado",
  "categoryId": "51e43257-7c25-4812-9d26-32ed6dc30509",
  "date": "2026-04-05"
}

###
# Listar transações
GET {{baseUrl}}/transactions?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI2ZTZhMjk5LTk2YTQtNGRlOC1hYTUxLTllNTA0MWFkZTM3MyIsImV4cCI6MTc3NTUwMTYwMCwiaXNzIjoiRmluVHJhY2suQXBpIiwiYXVkIjoiRmluVHJhY2suQ2xpZW50In0.wTDtnuRXPRkiTLsT0Lz1iuFFREu_AgXDQ6B3V25InQ8